package net.sourceforge.guacamole.net.auth.mysql.dao;

import java.util.List;
import net.sourceforge.guacamole.net.auth.mysql.model.Connection;
import net.sourceforge.guacamole.net.auth.mysql.model.ConnectionExample;
import org.apache.ibatis.annotations.Param;

public interface ConnectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_connection
     *
     * @mbggenerated Tue Feb 12 10:51:12 PST 2013
     */
    int countByExample(ConnectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_connection
     *
     * @mbggenerated Tue Feb 12 10:51:12 PST 2013
     */
    int deleteByExample(ConnectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_connection
     *
     * @mbggenerated Tue Feb 12 10:51:12 PST 2013
     */
    int deleteByPrimaryKey(Integer connection_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_connection
     *
     * @mbggenerated Tue Feb 12 10:51:12 PST 2013
     */
    int insert(Connection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_connection
     *
     * @mbggenerated Tue Feb 12 10:51:12 PST 2013
     */
    int insertSelective(Connection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_connection
     *
     * @mbggenerated Tue Feb 12 10:51:12 PST 2013
     */
    List<Connection> selectByExample(ConnectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_connection
     *
     * @mbggenerated Tue Feb 12 10:51:12 PST 2013
     */
    Connection selectByPrimaryKey(Integer connection_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_connection
     *
     * @mbggenerated Tue Feb 12 10:51:12 PST 2013
     */
    int updateByExampleSelective(@Param("record") Connection record, @Param("example") ConnectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_connection
     *
     * @mbggenerated Tue Feb 12 10:51:12 PST 2013
     */
    int updateByExample(@Param("record") Connection record, @Param("example") ConnectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_connection
     *
     * @mbggenerated Tue Feb 12 10:51:12 PST 2013
     */
    int updateByPrimaryKeySelective(Connection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_connection
     *
     * @mbggenerated Tue Feb 12 10:51:12 PST 2013
     */
    int updateByPrimaryKey(Connection record);
}