package net.sourceforge.guacamole.net.auth.mysql.dao;

import java.util.List;
import net.sourceforge.guacamole.net.auth.mysql.model.ConnectionHistory;
import net.sourceforge.guacamole.net.auth.mysql.model.ConnectionHistoryExample;
import org.apache.ibatis.annotations.Param;

public interface ConnectionHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_connection_history
     *
     * @mbggenerated Tue Feb 19 23:09:22 PST 2013
     */
    int countByExample(ConnectionHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_connection_history
     *
     * @mbggenerated Tue Feb 19 23:09:22 PST 2013
     */
    int deleteByExample(ConnectionHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_connection_history
     *
     * @mbggenerated Tue Feb 19 23:09:22 PST 2013
     */
    int deleteByPrimaryKey(Integer history_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_connection_history
     *
     * @mbggenerated Tue Feb 19 23:09:22 PST 2013
     */
    int insert(ConnectionHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_connection_history
     *
     * @mbggenerated Tue Feb 19 23:09:22 PST 2013
     */
    int insertSelective(ConnectionHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_connection_history
     *
     * @mbggenerated Tue Feb 19 23:09:22 PST 2013
     */
    List<ConnectionHistory> selectByExample(ConnectionHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_connection_history
     *
     * @mbggenerated Tue Feb 19 23:09:22 PST 2013
     */
    ConnectionHistory selectByPrimaryKey(Integer history_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_connection_history
     *
     * @mbggenerated Tue Feb 19 23:09:22 PST 2013
     */
    int updateByExampleSelective(@Param("record") ConnectionHistory record, @Param("example") ConnectionHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_connection_history
     *
     * @mbggenerated Tue Feb 19 23:09:22 PST 2013
     */
    int updateByExample(@Param("record") ConnectionHistory record, @Param("example") ConnectionHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_connection_history
     *
     * @mbggenerated Tue Feb 19 23:09:22 PST 2013
     */
    int updateByPrimaryKeySelective(ConnectionHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_connection_history
     *
     * @mbggenerated Tue Feb 19 23:09:22 PST 2013
     */
    int updateByPrimaryKey(ConnectionHistory record);
}