package net.sourceforge.guacamole.net.auth.mysql.dao;

import java.util.List;
import net.sourceforge.guacamole.net.auth.mysql.model.SystemPermissionExample;
import net.sourceforge.guacamole.net.auth.mysql.model.SystemPermissionKey;
import org.apache.ibatis.annotations.Param;

public interface SystemPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_system_permission
     *
     * @mbggenerated Tue Feb 19 23:09:22 PST 2013
     */
    int countByExample(SystemPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_system_permission
     *
     * @mbggenerated Tue Feb 19 23:09:22 PST 2013
     */
    int deleteByExample(SystemPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_system_permission
     *
     * @mbggenerated Tue Feb 19 23:09:22 PST 2013
     */
    int deleteByPrimaryKey(SystemPermissionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_system_permission
     *
     * @mbggenerated Tue Feb 19 23:09:22 PST 2013
     */
    int insert(SystemPermissionKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_system_permission
     *
     * @mbggenerated Tue Feb 19 23:09:22 PST 2013
     */
    int insertSelective(SystemPermissionKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_system_permission
     *
     * @mbggenerated Tue Feb 19 23:09:22 PST 2013
     */
    List<SystemPermissionKey> selectByExample(SystemPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_system_permission
     *
     * @mbggenerated Tue Feb 19 23:09:22 PST 2013
     */
    int updateByExampleSelective(@Param("record") SystemPermissionKey record, @Param("example") SystemPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_system_permission
     *
     * @mbggenerated Tue Feb 19 23:09:22 PST 2013
     */
    int updateByExample(@Param("record") SystemPermissionKey record, @Param("example") SystemPermissionExample example);
}