package net.sourceforge.guacamole.net.auth.mysql.dao;

import java.util.List;
import net.sourceforge.guacamole.net.auth.mysql.model.UserPermissionExample;
import net.sourceforge.guacamole.net.auth.mysql.model.UserPermissionKey;
import org.apache.ibatis.annotations.Param;

public interface UserPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_user_permission
     *
     * @mbggenerated Tue Feb 19 23:09:22 PST 2013
     */
    int countByExample(UserPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_user_permission
     *
     * @mbggenerated Tue Feb 19 23:09:22 PST 2013
     */
    int deleteByExample(UserPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_user_permission
     *
     * @mbggenerated Tue Feb 19 23:09:22 PST 2013
     */
    int deleteByPrimaryKey(UserPermissionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_user_permission
     *
     * @mbggenerated Tue Feb 19 23:09:22 PST 2013
     */
    int insert(UserPermissionKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_user_permission
     *
     * @mbggenerated Tue Feb 19 23:09:22 PST 2013
     */
    int insertSelective(UserPermissionKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_user_permission
     *
     * @mbggenerated Tue Feb 19 23:09:22 PST 2013
     */
    List<UserPermissionKey> selectByExample(UserPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_user_permission
     *
     * @mbggenerated Tue Feb 19 23:09:22 PST 2013
     */
    int updateByExampleSelective(@Param("record") UserPermissionKey record, @Param("example") UserPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_user_permission
     *
     * @mbggenerated Tue Feb 19 23:09:22 PST 2013
     */
    int updateByExample(@Param("record") UserPermissionKey record, @Param("example") UserPermissionExample example);
}