package net.sourceforge.guacamole.net.auth.mysql.dao;

import java.util.List;
import net.sourceforge.guacamole.net.auth.mysql.model.User;
import net.sourceforge.guacamole.net.auth.mysql.model.UserExample;
import net.sourceforge.guacamole.net.auth.mysql.model.UserWithBLOBs;
import org.apache.ibatis.annotations.Param;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_user
     *
     * @mbggenerated Tue Feb 12 10:51:12 PST 2013
     */
    int countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_user
     *
     * @mbggenerated Tue Feb 12 10:51:12 PST 2013
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_user
     *
     * @mbggenerated Tue Feb 12 10:51:12 PST 2013
     */
    int deleteByPrimaryKey(Integer user_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_user
     *
     * @mbggenerated Tue Feb 12 10:51:12 PST 2013
     */
    int insert(UserWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_user
     *
     * @mbggenerated Tue Feb 12 10:51:12 PST 2013
     */
    int insertSelective(UserWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_user
     *
     * @mbggenerated Tue Feb 12 10:51:12 PST 2013
     */
    List<UserWithBLOBs> selectByExampleWithBLOBs(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_user
     *
     * @mbggenerated Tue Feb 12 10:51:12 PST 2013
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_user
     *
     * @mbggenerated Tue Feb 12 10:51:12 PST 2013
     */
    UserWithBLOBs selectByPrimaryKey(Integer user_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_user
     *
     * @mbggenerated Tue Feb 12 10:51:12 PST 2013
     */
    int updateByExampleSelective(@Param("record") UserWithBLOBs record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_user
     *
     * @mbggenerated Tue Feb 12 10:51:12 PST 2013
     */
    int updateByExampleWithBLOBs(@Param("record") UserWithBLOBs record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_user
     *
     * @mbggenerated Tue Feb 12 10:51:12 PST 2013
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_user
     *
     * @mbggenerated Tue Feb 12 10:51:12 PST 2013
     */
    int updateByPrimaryKeySelective(UserWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_user
     *
     * @mbggenerated Tue Feb 12 10:51:12 PST 2013
     */
    int updateByPrimaryKeyWithBLOBs(UserWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_user
     *
     * @mbggenerated Tue Feb 12 10:51:12 PST 2013
     */
    int updateByPrimaryKey(User record);
}