package net.sourceforge.guacamole.net.auth.mysql.dao.guacamole;

import java.util.List;
import net.sourceforge.guacamole.net.auth.mysql.model.guacamole.User;
import net.sourceforge.guacamole.net.auth.mysql.model.guacamole.UserExample;
import org.apache.ibatis.annotations.Param;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_user
     *
     * @mbggenerated Tue Feb 05 15:45:11 PST 2013
     */
    int countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_user
     *
     * @mbggenerated Tue Feb 05 15:45:11 PST 2013
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_user
     *
     * @mbggenerated Tue Feb 05 15:45:11 PST 2013
     */
    int deleteByPrimaryKey(Integer user_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_user
     *
     * @mbggenerated Tue Feb 05 15:45:11 PST 2013
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_user
     *
     * @mbggenerated Tue Feb 05 15:45:11 PST 2013
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_user
     *
     * @mbggenerated Tue Feb 05 15:45:11 PST 2013
     */
    List<User> selectByExampleWithBLOBs(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_user
     *
     * @mbggenerated Tue Feb 05 15:45:11 PST 2013
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_user
     *
     * @mbggenerated Tue Feb 05 15:45:11 PST 2013
     */
    User selectByPrimaryKey(Integer user_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_user
     *
     * @mbggenerated Tue Feb 05 15:45:11 PST 2013
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_user
     *
     * @mbggenerated Tue Feb 05 15:45:11 PST 2013
     */
    int updateByExampleWithBLOBs(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_user
     *
     * @mbggenerated Tue Feb 05 15:45:11 PST 2013
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_user
     *
     * @mbggenerated Tue Feb 05 15:45:11 PST 2013
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_user
     *
     * @mbggenerated Tue Feb 05 15:45:11 PST 2013
     */
    int updateByPrimaryKeyWithBLOBs(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_user
     *
     * @mbggenerated Tue Feb 05 15:45:11 PST 2013
     */
    int updateByPrimaryKey(User record);
}