package net.sourceforge.guacamole.net.auth.mysql.model;

import java.util.ArrayList;
import java.util.List;

public class ConnectionParameterExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table guacamole..guacamole_connection_parameter
     *
     * @mbggenerated Tue Feb 19 23:09:22 PST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table guacamole..guacamole_connection_parameter
     *
     * @mbggenerated Tue Feb 19 23:09:22 PST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table guacamole..guacamole_connection_parameter
     *
     * @mbggenerated Tue Feb 19 23:09:22 PST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_connection_parameter
     *
     * @mbggenerated Tue Feb 19 23:09:22 PST 2013
     */
    public ConnectionParameterExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_connection_parameter
     *
     * @mbggenerated Tue Feb 19 23:09:22 PST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_connection_parameter
     *
     * @mbggenerated Tue Feb 19 23:09:22 PST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_connection_parameter
     *
     * @mbggenerated Tue Feb 19 23:09:22 PST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_connection_parameter
     *
     * @mbggenerated Tue Feb 19 23:09:22 PST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_connection_parameter
     *
     * @mbggenerated Tue Feb 19 23:09:22 PST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_connection_parameter
     *
     * @mbggenerated Tue Feb 19 23:09:22 PST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_connection_parameter
     *
     * @mbggenerated Tue Feb 19 23:09:22 PST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_connection_parameter
     *
     * @mbggenerated Tue Feb 19 23:09:22 PST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_connection_parameter
     *
     * @mbggenerated Tue Feb 19 23:09:22 PST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guacamole..guacamole_connection_parameter
     *
     * @mbggenerated Tue Feb 19 23:09:22 PST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table guacamole..guacamole_connection_parameter
     *
     * @mbggenerated Tue Feb 19 23:09:22 PST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andConnection_idIsNull() {
            addCriterion("connection_id is null");
            return (Criteria) this;
        }

        public Criteria andConnection_idIsNotNull() {
            addCriterion("connection_id is not null");
            return (Criteria) this;
        }

        public Criteria andConnection_idEqualTo(Integer value) {
            addCriterion("connection_id =", value, "connection_id");
            return (Criteria) this;
        }

        public Criteria andConnection_idNotEqualTo(Integer value) {
            addCriterion("connection_id <>", value, "connection_id");
            return (Criteria) this;
        }

        public Criteria andConnection_idGreaterThan(Integer value) {
            addCriterion("connection_id >", value, "connection_id");
            return (Criteria) this;
        }

        public Criteria andConnection_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("connection_id >=", value, "connection_id");
            return (Criteria) this;
        }

        public Criteria andConnection_idLessThan(Integer value) {
            addCriterion("connection_id <", value, "connection_id");
            return (Criteria) this;
        }

        public Criteria andConnection_idLessThanOrEqualTo(Integer value) {
            addCriterion("connection_id <=", value, "connection_id");
            return (Criteria) this;
        }

        public Criteria andConnection_idIn(List<Integer> values) {
            addCriterion("connection_id in", values, "connection_id");
            return (Criteria) this;
        }

        public Criteria andConnection_idNotIn(List<Integer> values) {
            addCriterion("connection_id not in", values, "connection_id");
            return (Criteria) this;
        }

        public Criteria andConnection_idBetween(Integer value1, Integer value2) {
            addCriterion("connection_id between", value1, value2, "connection_id");
            return (Criteria) this;
        }

        public Criteria andConnection_idNotBetween(Integer value1, Integer value2) {
            addCriterion("connection_id not between", value1, value2, "connection_id");
            return (Criteria) this;
        }

        public Criteria andParameter_nameIsNull() {
            addCriterion("parameter_name is null");
            return (Criteria) this;
        }

        public Criteria andParameter_nameIsNotNull() {
            addCriterion("parameter_name is not null");
            return (Criteria) this;
        }

        public Criteria andParameter_nameEqualTo(String value) {
            addCriterion("parameter_name =", value, "parameter_name");
            return (Criteria) this;
        }

        public Criteria andParameter_nameNotEqualTo(String value) {
            addCriterion("parameter_name <>", value, "parameter_name");
            return (Criteria) this;
        }

        public Criteria andParameter_nameGreaterThan(String value) {
            addCriterion("parameter_name >", value, "parameter_name");
            return (Criteria) this;
        }

        public Criteria andParameter_nameGreaterThanOrEqualTo(String value) {
            addCriterion("parameter_name >=", value, "parameter_name");
            return (Criteria) this;
        }

        public Criteria andParameter_nameLessThan(String value) {
            addCriterion("parameter_name <", value, "parameter_name");
            return (Criteria) this;
        }

        public Criteria andParameter_nameLessThanOrEqualTo(String value) {
            addCriterion("parameter_name <=", value, "parameter_name");
            return (Criteria) this;
        }

        public Criteria andParameter_nameLike(String value) {
            addCriterion("parameter_name like", value, "parameter_name");
            return (Criteria) this;
        }

        public Criteria andParameter_nameNotLike(String value) {
            addCriterion("parameter_name not like", value, "parameter_name");
            return (Criteria) this;
        }

        public Criteria andParameter_nameIn(List<String> values) {
            addCriterion("parameter_name in", values, "parameter_name");
            return (Criteria) this;
        }

        public Criteria andParameter_nameNotIn(List<String> values) {
            addCriterion("parameter_name not in", values, "parameter_name");
            return (Criteria) this;
        }

        public Criteria andParameter_nameBetween(String value1, String value2) {
            addCriterion("parameter_name between", value1, value2, "parameter_name");
            return (Criteria) this;
        }

        public Criteria andParameter_nameNotBetween(String value1, String value2) {
            addCriterion("parameter_name not between", value1, value2, "parameter_name");
            return (Criteria) this;
        }

        public Criteria andParameter_valueIsNull() {
            addCriterion("parameter_value is null");
            return (Criteria) this;
        }

        public Criteria andParameter_valueIsNotNull() {
            addCriterion("parameter_value is not null");
            return (Criteria) this;
        }

        public Criteria andParameter_valueEqualTo(String value) {
            addCriterion("parameter_value =", value, "parameter_value");
            return (Criteria) this;
        }

        public Criteria andParameter_valueNotEqualTo(String value) {
            addCriterion("parameter_value <>", value, "parameter_value");
            return (Criteria) this;
        }

        public Criteria andParameter_valueGreaterThan(String value) {
            addCriterion("parameter_value >", value, "parameter_value");
            return (Criteria) this;
        }

        public Criteria andParameter_valueGreaterThanOrEqualTo(String value) {
            addCriterion("parameter_value >=", value, "parameter_value");
            return (Criteria) this;
        }

        public Criteria andParameter_valueLessThan(String value) {
            addCriterion("parameter_value <", value, "parameter_value");
            return (Criteria) this;
        }

        public Criteria andParameter_valueLessThanOrEqualTo(String value) {
            addCriterion("parameter_value <=", value, "parameter_value");
            return (Criteria) this;
        }

        public Criteria andParameter_valueLike(String value) {
            addCriterion("parameter_value like", value, "parameter_value");
            return (Criteria) this;
        }

        public Criteria andParameter_valueNotLike(String value) {
            addCriterion("parameter_value not like", value, "parameter_value");
            return (Criteria) this;
        }

        public Criteria andParameter_valueIn(List<String> values) {
            addCriterion("parameter_value in", values, "parameter_value");
            return (Criteria) this;
        }

        public Criteria andParameter_valueNotIn(List<String> values) {
            addCriterion("parameter_value not in", values, "parameter_value");
            return (Criteria) this;
        }

        public Criteria andParameter_valueBetween(String value1, String value2) {
            addCriterion("parameter_value between", value1, value2, "parameter_value");
            return (Criteria) this;
        }

        public Criteria andParameter_valueNotBetween(String value1, String value2) {
            addCriterion("parameter_value not between", value1, value2, "parameter_value");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table guacamole..guacamole_connection_parameter
     *
     * @mbggenerated do_not_delete_during_merge Tue Feb 19 23:09:22 PST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table guacamole..guacamole_connection_parameter
     *
     * @mbggenerated Tue Feb 19 23:09:22 PST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}