package net.sourceforge.guacamole.net.auth.mysql.model;

import java.util.Date;

public class ConnectionHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guacamole..guacamole_connection_history.history_id
     *
     * @mbggenerated Tue Feb 19 23:09:22 PST 2013
     */
    private Integer history_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guacamole..guacamole_connection_history.user_id
     *
     * @mbggenerated Tue Feb 19 23:09:22 PST 2013
     */
    private Integer user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guacamole..guacamole_connection_history.connection_id
     *
     * @mbggenerated Tue Feb 19 23:09:22 PST 2013
     */
    private Integer connection_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guacamole..guacamole_connection_history.start_date
     *
     * @mbggenerated Tue Feb 19 23:09:22 PST 2013
     */
    private Date start_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guacamole..guacamole_connection_history.end_date
     *
     * @mbggenerated Tue Feb 19 23:09:22 PST 2013
     */
    private Date end_date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guacamole..guacamole_connection_history.history_id
     *
     * @return the value of guacamole..guacamole_connection_history.history_id
     *
     * @mbggenerated Tue Feb 19 23:09:22 PST 2013
     */
    public Integer getHistory_id() {
        return history_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guacamole..guacamole_connection_history.history_id
     *
     * @param history_id the value for guacamole..guacamole_connection_history.history_id
     *
     * @mbggenerated Tue Feb 19 23:09:22 PST 2013
     */
    public void setHistory_id(Integer history_id) {
        this.history_id = history_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guacamole..guacamole_connection_history.user_id
     *
     * @return the value of guacamole..guacamole_connection_history.user_id
     *
     * @mbggenerated Tue Feb 19 23:09:22 PST 2013
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guacamole..guacamole_connection_history.user_id
     *
     * @param user_id the value for guacamole..guacamole_connection_history.user_id
     *
     * @mbggenerated Tue Feb 19 23:09:22 PST 2013
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guacamole..guacamole_connection_history.connection_id
     *
     * @return the value of guacamole..guacamole_connection_history.connection_id
     *
     * @mbggenerated Tue Feb 19 23:09:22 PST 2013
     */
    public Integer getConnection_id() {
        return connection_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guacamole..guacamole_connection_history.connection_id
     *
     * @param connection_id the value for guacamole..guacamole_connection_history.connection_id
     *
     * @mbggenerated Tue Feb 19 23:09:22 PST 2013
     */
    public void setConnection_id(Integer connection_id) {
        this.connection_id = connection_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guacamole..guacamole_connection_history.start_date
     *
     * @return the value of guacamole..guacamole_connection_history.start_date
     *
     * @mbggenerated Tue Feb 19 23:09:22 PST 2013
     */
    public Date getStart_date() {
        return start_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guacamole..guacamole_connection_history.start_date
     *
     * @param start_date the value for guacamole..guacamole_connection_history.start_date
     *
     * @mbggenerated Tue Feb 19 23:09:22 PST 2013
     */
    public void setStart_date(Date start_date) {
        this.start_date = start_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guacamole..guacamole_connection_history.end_date
     *
     * @return the value of guacamole..guacamole_connection_history.end_date
     *
     * @mbggenerated Tue Feb 19 23:09:22 PST 2013
     */
    public Date getEnd_date() {
        return end_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guacamole..guacamole_connection_history.end_date
     *
     * @param end_date the value for guacamole..guacamole_connection_history.end_date
     *
     * @mbggenerated Tue Feb 19 23:09:22 PST 2013
     */
    public void setEnd_date(Date end_date) {
        this.end_date = end_date;
    }
}