package net.sourceforge.guacamole.net.auth.mysql.model;

public class ConnectionParameter extends ConnectionParameterKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guacamole..guacamole_connection_parameter.parameter_value
     *
     * @mbggenerated Tue Feb 12 10:51:12 PST 2013
     */
    private String parameter_value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guacamole..guacamole_connection_parameter.parameter_value
     *
     * @return the value of guacamole..guacamole_connection_parameter.parameter_value
     *
     * @mbggenerated Tue Feb 12 10:51:12 PST 2013
     */
    public String getParameter_value() {
        return parameter_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guacamole..guacamole_connection_parameter.parameter_value
     *
     * @param parameter_value the value for guacamole..guacamole_connection_parameter.parameter_value
     *
     * @mbggenerated Tue Feb 12 10:51:12 PST 2013
     */
    public void setParameter_value(String parameter_value) {
        this.parameter_value = parameter_value;
    }
}