package net.sourceforge.guacamole.net.auth.mysql.model;

public class ConnectionParameterKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guacamole..guacamole_connection_parameter.connection_id
     *
     * @mbggenerated Tue Feb 12 20:35:54 PST 2013
     */
    private Integer connection_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guacamole..guacamole_connection_parameter.parameter_name
     *
     * @mbggenerated Tue Feb 12 20:35:54 PST 2013
     */
    private String parameter_name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guacamole..guacamole_connection_parameter.connection_id
     *
     * @return the value of guacamole..guacamole_connection_parameter.connection_id
     *
     * @mbggenerated Tue Feb 12 20:35:54 PST 2013
     */
    public Integer getConnection_id() {
        return connection_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guacamole..guacamole_connection_parameter.connection_id
     *
     * @param connection_id the value for guacamole..guacamole_connection_parameter.connection_id
     *
     * @mbggenerated Tue Feb 12 20:35:54 PST 2013
     */
    public void setConnection_id(Integer connection_id) {
        this.connection_id = connection_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guacamole..guacamole_connection_parameter.parameter_name
     *
     * @return the value of guacamole..guacamole_connection_parameter.parameter_name
     *
     * @mbggenerated Tue Feb 12 20:35:54 PST 2013
     */
    public String getParameter_name() {
        return parameter_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guacamole..guacamole_connection_parameter.parameter_name
     *
     * @param parameter_name the value for guacamole..guacamole_connection_parameter.parameter_name
     *
     * @mbggenerated Tue Feb 12 20:35:54 PST 2013
     */
    public void setParameter_name(String parameter_name) {
        this.parameter_name = parameter_name;
    }
}