package net.sourceforge.guacamole.net.auth.mysql.model;

public class Connection {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guacamole..guacamole_connection.connection_id
     *
     * @mbggenerated Tue Feb 12 10:51:12 PST 2013
     */
    private Integer connection_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guacamole..guacamole_connection.connection_name
     *
     * @mbggenerated Tue Feb 12 10:51:12 PST 2013
     */
    private String connection_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guacamole..guacamole_connection.protocol
     *
     * @mbggenerated Tue Feb 12 10:51:12 PST 2013
     */
    private String protocol;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guacamole..guacamole_connection.connection_id
     *
     * @return the value of guacamole..guacamole_connection.connection_id
     *
     * @mbggenerated Tue Feb 12 10:51:12 PST 2013
     */
    public Integer getConnection_id() {
        return connection_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guacamole..guacamole_connection.connection_id
     *
     * @param connection_id the value for guacamole..guacamole_connection.connection_id
     *
     * @mbggenerated Tue Feb 12 10:51:12 PST 2013
     */
    public void setConnection_id(Integer connection_id) {
        this.connection_id = connection_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guacamole..guacamole_connection.connection_name
     *
     * @return the value of guacamole..guacamole_connection.connection_name
     *
     * @mbggenerated Tue Feb 12 10:51:12 PST 2013
     */
    public String getConnection_name() {
        return connection_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guacamole..guacamole_connection.connection_name
     *
     * @param connection_name the value for guacamole..guacamole_connection.connection_name
     *
     * @mbggenerated Tue Feb 12 10:51:12 PST 2013
     */
    public void setConnection_name(String connection_name) {
        this.connection_name = connection_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guacamole..guacamole_connection.protocol
     *
     * @return the value of guacamole..guacamole_connection.protocol
     *
     * @mbggenerated Tue Feb 12 10:51:12 PST 2013
     */
    public String getProtocol() {
        return protocol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guacamole..guacamole_connection.protocol
     *
     * @param protocol the value for guacamole..guacamole_connection.protocol
     *
     * @mbggenerated Tue Feb 12 10:51:12 PST 2013
     */
    public void setProtocol(String protocol) {
        this.protocol = protocol;
    }
}