package net.sourceforge.guacamole.net.auth.mysql.model;

public class UserWithBLOBs extends User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guacamole..guacamole_user.password_hash
     *
     * @mbggenerated Tue Feb 12 20:35:54 PST 2013
     */
    private byte[] password_hash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guacamole..guacamole_user.password_salt
     *
     * @mbggenerated Tue Feb 12 20:35:54 PST 2013
     */
    private byte[] password_salt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guacamole..guacamole_user.password_hash
     *
     * @return the value of guacamole..guacamole_user.password_hash
     *
     * @mbggenerated Tue Feb 12 20:35:54 PST 2013
     */
    public byte[] getPassword_hash() {
        return password_hash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guacamole..guacamole_user.password_hash
     *
     * @param password_hash the value for guacamole..guacamole_user.password_hash
     *
     * @mbggenerated Tue Feb 12 20:35:54 PST 2013
     */
    public void setPassword_hash(byte[] password_hash) {
        this.password_hash = password_hash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guacamole..guacamole_user.password_salt
     *
     * @return the value of guacamole..guacamole_user.password_salt
     *
     * @mbggenerated Tue Feb 12 20:35:54 PST 2013
     */
    public byte[] getPassword_salt() {
        return password_salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guacamole..guacamole_user.password_salt
     *
     * @param password_salt the value for guacamole..guacamole_user.password_salt
     *
     * @mbggenerated Tue Feb 12 20:35:54 PST 2013
     */
    public void setPassword_salt(byte[] password_salt) {
        this.password_salt = password_salt;
    }
}