package net.sourceforge.guacamole.net.auth.mysql.model;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guacamole..guacamole_user.user_id
     *
     * @mbggenerated Tue Feb 12 10:51:12 PST 2013
     */
    private Integer user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guacamole..guacamole_user.username
     *
     * @mbggenerated Tue Feb 12 10:51:12 PST 2013
     */
    private String username;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guacamole..guacamole_user.user_id
     *
     * @return the value of guacamole..guacamole_user.user_id
     *
     * @mbggenerated Tue Feb 12 10:51:12 PST 2013
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guacamole..guacamole_user.user_id
     *
     * @param user_id the value for guacamole..guacamole_user.user_id
     *
     * @mbggenerated Tue Feb 12 10:51:12 PST 2013
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guacamole..guacamole_user.username
     *
     * @return the value of guacamole..guacamole_user.username
     *
     * @mbggenerated Tue Feb 12 10:51:12 PST 2013
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guacamole..guacamole_user.username
     *
     * @param username the value for guacamole..guacamole_user.username
     *
     * @mbggenerated Tue Feb 12 10:51:12 PST 2013
     */
    public void setUsername(String username) {
        this.username = username;
    }
}