/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

/**
 * Controller for the "GUAC_TOTP_CODE" field which prompts the user to enter
 * the code generated by their authentication device.
 */
angular.module('guacTOTP').controller('totpResetFieldController', ['$scope', '$window',
        function totpResetFieldController($scope, $window) {

    var origValue = $scope.model;
            
    // Update typed value when model is changed
    $scope.$watch('model', function modelChanged(model) {
        if (!model || model === '')
            $scope.typedValue = true;
        else
            $scope.typedValue = false;
    });

    // Update string value in model when typed value is changed
    $scope.$watch('typedValue', function typedValueChanged(typedValue) {
        if (typedValue && typedValue !== '')
            $scope.model = '';
        
        else
            $scope.model = origValue;
    });
        
}]);