package net.sourceforge.guacamole.net.auth.mysql.model.guacamole;

public class ConnectionPermissionKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guacamole..guacamole_connection_permission.user_id
     *
     * @mbggenerated Tue Feb 05 15:45:11 PST 2013
     */
    private Integer user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guacamole..guacamole_connection_permission.connection_id
     *
     * @mbggenerated Tue Feb 05 15:45:11 PST 2013
     */
    private Integer connection_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guacamole..guacamole_connection_permission.permission
     *
     * @mbggenerated Tue Feb 05 15:45:11 PST 2013
     */
    private String permission;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guacamole..guacamole_connection_permission.user_id
     *
     * @return the value of guacamole..guacamole_connection_permission.user_id
     *
     * @mbggenerated Tue Feb 05 15:45:11 PST 2013
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guacamole..guacamole_connection_permission.user_id
     *
     * @param user_id the value for guacamole..guacamole_connection_permission.user_id
     *
     * @mbggenerated Tue Feb 05 15:45:11 PST 2013
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guacamole..guacamole_connection_permission.connection_id
     *
     * @return the value of guacamole..guacamole_connection_permission.connection_id
     *
     * @mbggenerated Tue Feb 05 15:45:11 PST 2013
     */
    public Integer getConnection_id() {
        return connection_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guacamole..guacamole_connection_permission.connection_id
     *
     * @param connection_id the value for guacamole..guacamole_connection_permission.connection_id
     *
     * @mbggenerated Tue Feb 05 15:45:11 PST 2013
     */
    public void setConnection_id(Integer connection_id) {
        this.connection_id = connection_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guacamole..guacamole_connection_permission.permission
     *
     * @return the value of guacamole..guacamole_connection_permission.permission
     *
     * @mbggenerated Tue Feb 05 15:45:11 PST 2013
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guacamole..guacamole_connection_permission.permission
     *
     * @param permission the value for guacamole..guacamole_connection_permission.permission
     *
     * @mbggenerated Tue Feb 05 15:45:11 PST 2013
     */
    public void setPermission(String permission) {
        this.permission = permission == null ? null : permission.trim();
    }
}