package net.sourceforge.guacamole.net.auth.mysql.model.guacamole;

public class UserPermissionKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guacamole..guacamole_user_permission.user_id
     *
     * @mbggenerated Tue Feb 05 15:45:11 PST 2013
     */
    private Integer user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guacamole..guacamole_user_permission.affected_user_id
     *
     * @mbggenerated Tue Feb 05 15:45:11 PST 2013
     */
    private Integer affected_user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guacamole..guacamole_user_permission.permission
     *
     * @mbggenerated Tue Feb 05 15:45:11 PST 2013
     */
    private String permission;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guacamole..guacamole_user_permission.user_id
     *
     * @return the value of guacamole..guacamole_user_permission.user_id
     *
     * @mbggenerated Tue Feb 05 15:45:11 PST 2013
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guacamole..guacamole_user_permission.user_id
     *
     * @param user_id the value for guacamole..guacamole_user_permission.user_id
     *
     * @mbggenerated Tue Feb 05 15:45:11 PST 2013
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guacamole..guacamole_user_permission.affected_user_id
     *
     * @return the value of guacamole..guacamole_user_permission.affected_user_id
     *
     * @mbggenerated Tue Feb 05 15:45:11 PST 2013
     */
    public Integer getAffected_user_id() {
        return affected_user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guacamole..guacamole_user_permission.affected_user_id
     *
     * @param affected_user_id the value for guacamole..guacamole_user_permission.affected_user_id
     *
     * @mbggenerated Tue Feb 05 15:45:11 PST 2013
     */
    public void setAffected_user_id(Integer affected_user_id) {
        this.affected_user_id = affected_user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guacamole..guacamole_user_permission.permission
     *
     * @return the value of guacamole..guacamole_user_permission.permission
     *
     * @mbggenerated Tue Feb 05 15:45:11 PST 2013
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guacamole..guacamole_user_permission.permission
     *
     * @param permission the value for guacamole..guacamole_user_permission.permission
     *
     * @mbggenerated Tue Feb 05 15:45:11 PST 2013
     */
    public void setPermission(String permission) {
        this.permission = permission == null ? null : permission.trim();
    }
}