package net.sourceforge.guacamole.net.auth.mysql.model.guacamole;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guacamole..guacamole_user.user_id
     *
     * @mbggenerated Tue Feb 05 15:45:11 PST 2013
     */
    private Integer user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guacamole..guacamole_user.username
     *
     * @mbggenerated Tue Feb 05 15:45:11 PST 2013
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guacamole..guacamole_user.password_salt
     *
     * @mbggenerated Tue Feb 05 15:45:11 PST 2013
     */
    private String password_salt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guacamole..guacamole_user.password_hash
     *
     * @mbggenerated Tue Feb 05 15:45:11 PST 2013
     */
    private byte[] password_hash;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guacamole..guacamole_user.user_id
     *
     * @return the value of guacamole..guacamole_user.user_id
     *
     * @mbggenerated Tue Feb 05 15:45:11 PST 2013
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guacamole..guacamole_user.user_id
     *
     * @param user_id the value for guacamole..guacamole_user.user_id
     *
     * @mbggenerated Tue Feb 05 15:45:11 PST 2013
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guacamole..guacamole_user.username
     *
     * @return the value of guacamole..guacamole_user.username
     *
     * @mbggenerated Tue Feb 05 15:45:11 PST 2013
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guacamole..guacamole_user.username
     *
     * @param username the value for guacamole..guacamole_user.username
     *
     * @mbggenerated Tue Feb 05 15:45:11 PST 2013
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guacamole..guacamole_user.password_salt
     *
     * @return the value of guacamole..guacamole_user.password_salt
     *
     * @mbggenerated Tue Feb 05 15:45:11 PST 2013
     */
    public String getPassword_salt() {
        return password_salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guacamole..guacamole_user.password_salt
     *
     * @param password_salt the value for guacamole..guacamole_user.password_salt
     *
     * @mbggenerated Tue Feb 05 15:45:11 PST 2013
     */
    public void setPassword_salt(String password_salt) {
        this.password_salt = password_salt == null ? null : password_salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guacamole..guacamole_user.password_hash
     *
     * @return the value of guacamole..guacamole_user.password_hash
     *
     * @mbggenerated Tue Feb 05 15:45:11 PST 2013
     */
    public byte[] getPassword_hash() {
        return password_hash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guacamole..guacamole_user.password_hash
     *
     * @param password_hash the value for guacamole..guacamole_user.password_hash
     *
     * @mbggenerated Tue Feb 05 15:45:11 PST 2013
     */
    public void setPassword_hash(byte[] password_hash) {
        this.password_hash = password_hash;
    }
}