/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.apache.guacamole.vault.openbao.secret;

import org.bouncycastle.asn1.pkcs.PrivateKeyInfo;
import org.bouncycastle.crypto.AsymmetricCipherKeyPair;
import org.bouncycastle.crypto.generators.RSAKeyPairGenerator;
import org.bouncycastle.crypto.params.Ed25519PrivateKeyParameters;
import org.bouncycastle.crypto.params.Ed25519PublicKeyParameters;
import org.bouncycastle.crypto.params.RSAKeyGenerationParameters;
import org.bouncycastle.crypto.params.RSAPrivateCrtKeyParameters;
import org.bouncycastle.crypto.params.RSAKeyParameters;
import org.bouncycastle.crypto.util.PrivateKeyInfoFactory;
import org.bouncycastle.openssl.jcajce.JcaPEMWriter;
import org.apache.guacamole.vault.openbao.conf.OpenBaoConfigurationService;
import java.io.ByteArrayOutputStream;
import java.io.StringWriter;
import java.math.BigInteger;
import java.nio.charset.StandardCharsets;
import java.security.SecureRandom;
import java.util.Base64;
import java.util.Map;

public class OpenBaoSshKeys {

    /**
     * The PEM encoded private SSH key
     */
    public String privateSshPem;

    /**
     * The OpenSSH encoded public SSH key
     */
    public String publicSsh;

    /**
     * Class instantiation to return generated SSH keys
     */
    public OpenBaoSshKeys(String type) {
        if (type == "rsa") {
            RSAKeyPairGenerator generator = new RSAKeyPairGenerator();
            RSAKeyGenerationParameters params =
                    new RSAKeyGenerationParameters(
                            BigInteger.valueOf(0x10001), // public exponent (65537)
                            new SecureRandom(),
                            4096,                         // key size
                            80                            // certainty
                    );
            generator.init(params);
            AsymmetricCipherKeyPair keyPair = generator.generateKeyPair();
            publicSsh = toOpenSshPublicKey((RSAKeyParameters) keyPair.getPublic());
            privateSshPem = toOpenSshPrivateKey((RSAPrivateCrtKeyParameters) keyPair.getPrivate(), 
                    (RSAKeyParameters) keyPair.getPublic(), null);
        }
        else {
            SecureRandom random = new SecureRandom();

            Ed25519PrivateKeyParameters privateKey =
                    new Ed25519PrivateKeyParameters(random);

            Ed25519PublicKeyParameters publicKey =
                    privateKey.generatePublicKey();

            publicSsh = toOpenSshPublicKey(publicKey);
            privateSshPem = toOpenSshPrivateKey(privateKey);
        }
    }

    /**
     * Class instantiation to return generated SSH keys. Default type
     */
    public OpenBaoSshKeys() {
        this(OpenBaoConfigurationService.DEFAULT_SSH_TYPE);
    }

    /**
     * Generate OpenSSH encode ED25519 public key
     *
     * @param Ed25519PublicKeyParameters pubicKey
     *     The public key generated by BouncyCastle
     *
     * @return String
     *      The OpenSSH encoded ED25519 public key
     */
    private static String toOpenSshPublicKey(Ed25519PublicKeyParameters publicKey) {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        writeBytes(out, "ssh-ed25519".getBytes(StandardCharsets.US_ASCII));
        writeBytes(out, publicKey.getEncoded());

        String encoded = Base64.getEncoder().encodeToString(out.toByteArray());
        return "ssh-ed25519 " + encoded;
    }

    /**
     * Generate OpenSSH encode RSA public key
     *
     * @param RSAKeyParameters publicKey
     *     The public key generated by BouncyCastle
     *
     * @return String
     *      The OpenSSH encoded RSA public key
     */
    private static String toOpenSshPublicKey(RSAKeyParameters publicKey) {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        writeBytes(out, "ssh-rsa".getBytes(StandardCharsets.US_ASCII));
        writeBytes(out, publicKey.getExponent().toByteArray());
        writeBytes(out, publicKey.getModulus().toByteArray());
        String encoded = Base64.getEncoder().encodeToString(out.toByteArray());

        return "ssh-rsa " + encoded;
    }

    /**
     * Generate OpenSSH encode ed25519 private key
     *
     * @param Ed25519PrivateKeyParameters privateKey)
     *     The private key generated by BouncyCastle
     *
     * @return String
     *      The OpenSSH encoded ED25519 private key
     */
    private static String toOpenSshPrivateKey(Ed25519PrivateKeyParameters privateKey) {
        byte[] raw = privateKey.getEncoded();
        String base64 = Base64.getEncoder().encodeToString(raw);

        return String.format(
                "-----BEGIN OPENSSH PRIVATE KEY-----%n%s%n" +
                " -----END OPENSSH PRIVATE KEY-----%n", base64);
    }

    /**
     * Guacamole needs private key in OpenSSH format, which is officially undocumented,
     * so this is an ugly function to write RSA private keys in OpenSSH format
     *
     * @param RSAPrivateCrtKeyParameter privateKey
     *      The RSA private key generated by BouncyCastle
     *
     * @param RSAKeyParameters publicKey
     *      The RSA public key generated by BouncyCastle
     *
     * @param String comment
     *      An arbitrary comment that can be added to the private key
     *
     * @return String
     *      The OpenSSH encoded RSA private key
     */
    private static String toOpenSshPrivateKey(
            RSAPrivateCrtKeyParameters privateKey,
            RSAKeyParameters publicKey,
            String comment) {

        try {
            SecureRandom rnd = new SecureRandom();
            ByteArrayOutputStream out = new ByteArrayOutputStream();

            // header
            writeBytes(out, "openssh-key-v1\0".getBytes(StandardCharsets.UTF_8));
            writeBytes(out, "none".getBytes(StandardCharsets.UTF_8)); // cipher
            writeBytes(out, "none".getBytes(StandardCharsets.UTF_8)); // kdf
            writeBytes(out, new byte[0]);                             // kdf options
            writeInt(out, 1);                                         // number of keys

            // write public key blob
            ByteArrayOutputStream pubOut = new ByteArrayOutputStream();
            writeBytes(pubOut, "ssh-rsa".getBytes(StandardCharsets.UTF_8));
            writeBytes(pubOut, publicKey.getExponent().toByteArray());
            writeBytes(pubOut, publicKey.getModulus().toByteArray());
            writeBytes(out, pubOut.toByteArray());

            // private key block
            ByteArrayOutputStream privOut = new ByteArrayOutputStream();

            int check = rnd.nextInt();
            writeInt(privOut, check);
            writeInt(privOut, check);

            writeBytes(privOut, "ssh-rsa".getBytes(StandardCharsets.UTF_8));
            writeBytes(privOut, publicKey.getModulus().toByteArray());
            writeBytes(privOut, publicKey.getExponent().toByteArray());
            writeBytes(privOut, privateKey.getExponent().toByteArray());
            writeBytes(privOut, privateKey.getQInv().toByteArray());
            writeBytes(privOut, privateKey.getP().toByteArray());
            writeBytes(privOut, privateKey.getQ().toByteArray());
            writeBytes(privOut,
                (comment == null ? "" : comment).getBytes(StandardCharsets.UTF_8));

            pad(privOut);

            writeBytes(out, privOut.toByteArray());

            String base64 =
                Base64.getMimeEncoder(70, new byte[]{'\n'})
                      .encodeToString(out.toByteArray());

            return String.format(
                    "-----BEGIN OPENSSH PRIVATE KEY-----%n%s%n" +
                    " -----END OPENSSH PRIVATE KEY-----%n", base64);

        } catch (Exception e) {
            throw new IllegalStateException(e);
        }
    }

   /**
    * Pad output stream to 8 byte boundary
    *
    * @param ByteArrAyOutputStream
    *     The byte stream to be padded
    */
    private static void pad(ByteArrayOutputStream out) {
        int padLen = 8 - (out.size() % 8);
        for (int i = 1; i <= padLen; i++) {
            out.write(i);
        }
    }

    /**
     * Helper function toan int in OpenSSH key format
     *
     * @param ByteArrayOutputStream
     *     The stream on which to write the result
     *
     * @param int
     *     The int to convert and write to the stream
     */
    private static void writeInt(ByteArrayOutputStream out, int v) {
        out.write((v >>> 24) & 0xff);
        out.write((v >>> 16) & 0xff);
        out.write((v >>> 8) & 0xff);
        out.write(v & 0xff);
    }

    /**
     * Helper function to write bytes to OpenSSH key format
     *
     * @param ByteArrayOutputStream
     *     The stream on which to write the result
     *
     * @param byte[]
     *     The byte array to convert and write to the stream
     */
    private static void writeBytes(ByteArrayOutputStream out, byte[] b) {
        writeInt(out, b.length);
        out.write(b, 0, b.length);
    }
}
