/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.apache.guacamole.auth.duo.conf;

import com.google.inject.Inject;
import inet.ipaddr.IPAddress;
import java.util.Collections;
import java.util.List;
import org.apache.guacamole.GuacamoleException;
import org.apache.guacamole.environment.Environment;
import org.apache.guacamole.properties.IPAddressListProperty;
import org.apache.guacamole.properties.StringGuacamoleProperty;

/**
 * Service for retrieving configuration information regarding the Duo
 * authentication extension.
 */
public class ConfigurationService {

    /**
     * The Guacamole server environment.
     */
    @Inject
    private Environment environment;

    /**
     * The property within guacamole.properties which defines the hostname
     * of the Duo API endpoint to be used to verify user identities. This will
     * usually be in the form "api-XXXXXXXX.duosecurity.com", where "XXXXXXXX"
     * is some arbitrary alphanumeric value assigned by Duo and specific to
     * your organization.
     */
    private static final StringGuacamoleProperty DUO_API_HOSTNAME =
            new StringGuacamoleProperty() {

        @Override
        public String getName() { return "duo-api-hostname"; }

    };

    /**
     * The property within guacamole.properties which defines the integration
     * key received from Duo for verifying Guacamole users. This value MUST be
     * exactly 20 characters.
     */
    private static final StringGuacamoleProperty DUO_INTEGRATION_KEY =
            new StringGuacamoleProperty() {

        @Override
        public String getName() { return "duo-integration-key"; }

    };

    /**
     * The property within guacamole.properties which defines the secret key
     * received from Duo for verifying Guacamole users. This value MUST be
     * exactly 40 characters.
     */
    private static final StringGuacamoleProperty DUO_SECRET_KEY =
            new StringGuacamoleProperty() {

        @Override
        public String getName() { return "duo-secret-key"; }

    };

    /**
     * The property within guacamole.properties which defines the arbitrary
     * random key which was generated for Guacamole. Note that this value is not
     * provided by Duo, but is expected to be generated by the administrator of
     * the system hosting Guacamole. This value MUST be at least 40 characters.
     */
    private static final StringGuacamoleProperty DUO_APPLICATION_KEY =
            new StringGuacamoleProperty() {

        @Override
        public String getName() { return "duo-application-key"; }

    };
    
    /**
     * The optional property that contains a comma-separated list of IP addresses
     * or CIDRs for which the MFA requirement should be bypassed. If the Duo
     * extension is installed, any/all users authenticating from clients that
     * match this list will be able to successfully log in without fulfilling
     * the MFA requirement. If this option is omitted or is empty, and the
     * Duo module is installed, all users from all hosts will have Duo MFA
     * enforced.
     */
    private static final IPAddressListProperty DUO_BYPASS_HOSTS =
            new IPAddressListProperty() {
    
        @Override
        public String getName() { return "duo-bypass-hosts"; }
                
    };
        
    /**
     * The optional property that contains a comma-separated list of IP addresses
     * or CIDRs for which the MFA requirement should be explicitly enforced. If
     * the Duo module is enabled and this property is specified, users that log
     * in from hosts that match the items in this list will have Duo MFA required,
     * and all users from hosts that do not match this list will be able to log
     * in without the MFA requirement. If this option is missing or empty and
     * the Duo module is installed, MFA will be enforced for all users.
     */
    private static final IPAddressListProperty DUO_ENFORCE_HOSTS =
            new IPAddressListProperty() {
    
        @Override
        public String getName() { return "duo-enforce-hosts"; }
                
    };

    /**
     * Returns the hostname of the Duo API endpoint to be used to verify user
     * identities, as defined in guacamole.properties by the "duo-api-hostname"
     * property. This will usually be in the form
     * "api-XXXXXXXX.duosecurity.com", where "XXXXXXXX" is some arbitrary
     * alphanumeric value assigned by Duo and specific to your organization.
     *
     * @return
     *     The hostname of the Duo API endpoint to be used to verify user
     *     identities.
     *
     * @throws GuacamoleException
     *     If the associated property within guacamole.properties is missing.
     */
    public String getAPIHostname() throws GuacamoleException {
        return environment.getRequiredProperty(DUO_API_HOSTNAME);
    }

    /**
     * Returns the integration key received from Duo for verifying Guacamole
     * users, as defined in guacamole.properties by the "duo-integration-key"
     * property. This value MUST be exactly 20 characters.
     *
     * @return
     *     The integration key received from Duo for verifying Guacamole
     *     users.
     *
     * @throws GuacamoleException
     *     If the associated property within guacamole.properties is missing.
     */
    public String getIntegrationKey() throws GuacamoleException {
        return environment.getRequiredProperty(DUO_INTEGRATION_KEY);
    }

    /**
     * Returns the secret key received from Duo for verifying Guacamole users,
     * as defined in guacamole.properties by the "duo-secret-key" property. This
     * value MUST be exactly 20 characters.
     *
     * @return
     *     The secret key received from Duo for verifying Guacamole users.
     *
     * @throws GuacamoleException
     *     If the associated property within guacamole.properties is missing.
     */
    public String getSecretKey() throws GuacamoleException {
        return environment.getRequiredProperty(DUO_SECRET_KEY);
    }

    /**
     * Returns the arbitrary random key which was generated for Guacamole, as
     * defined in guacamole.properties by the "duo-application-key" property.
     * Note that this value is not provided by Duo, but is expected to be
     * generated by the administrator of the system hosting Guacamole. This
     * value MUST be at least 40 characters.
     *
     * @return
     *     The arbitrary random key which was generated for Guacamole.
     *
     * @throws GuacamoleException
     *     If the associated property within guacamole.properties is missing.
     */
    public String getApplicationKey() throws GuacamoleException {
        return environment.getRequiredProperty(DUO_APPLICATION_KEY);
    }
    
    /**
     * Returns the list of IP addresses and subnets defined in guacamole.properties
     * for which Duo MFA should _not_ be enforced. Users logging in from hosts
     * contained in this list will be logged in without the MFA requirement.
     * 
     * @return
     *     A list of IP addresses and subnets for which Duo MFA should not be
     *     enforced.
     * 
     * @throws GuacamoleException 
     *     If guacamole.properties cannot be parsed, or if an invalid IP address
     *     or subnet is specified.
     */
    public List<IPAddress> getBypassHosts() throws GuacamoleException {
        return environment.getProperty(DUO_BYPASS_HOSTS, Collections.emptyList());
    }
    
    /**
     * Returns the list of IP addresses and subnets defined in guacamole.properties
     * for which Duo MFA should explicitly be enforced, while logins from all
     * other hosts should not enforce MFA. Users logging in from hosts
     * contained in this list will be required to complete the Duo MFA authentication,
     * while users from all other hosts will be logged in without the MFA requirement.
     * 
     * @return
     *     A list of IP addresses and subnets for which Duo MFA should be
     *     explicitly enforced.
     * 
     * @throws GuacamoleException 
     *     If guacamole.properties cannot be parsed, or if an invalid IP address
     *     or subnet is specified.
     */
    public List<IPAddress> getEnforceHosts() throws GuacamoleException {
        return environment.getProperty(DUO_ENFORCE_HOSTS, Collections.emptyList());
    }
    
    

}
