/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

const webpack = require('webpack');
const ClosureWebpackPlugin = require('closure-webpack-plugin');

module.exports = {

    bail: true,
    mode: 'production',

    output: {
        path: __dirname + '/dist',
        filename: 'guacamole.min.js'
    },

    // Generate source maps, automatically building off any source maps
    // generated by Gulp
    devtool: 'source-map',
    module: {
        rules: [
            {
                test: /\.js$/,
                enforce: 'pre',
                use: [ 'source-map-loader' ]
            }
        ]
    },

    // Automatically require used modules
    plugins: [
        new webpack.ProvidePlugin({
            $: 'jquery',
            _: 'lodash',
            angular: 'angular',
            jstz: 'jstz',
            Pickr: '@simonwep/pickr',
            saveAs: 'file-saver'
        })
    ],

    // Minify using Google Closure Compiler
    optimization: {
        minimizer: [
            new ClosureWebpackPlugin({ mode: 'STANDARD' }, {
                externs: 'externs.js',
                languageIn: 'ECMASCRIPT6',
                languageOut: 'ECMASCRIPT5',
                compilationLevel: 'ADVANCED'
            })
        ]
    }

};

